  apiVersion: v1
  kind: BuildConfig
  metadata: 
    labels: 
      build: coolstore
    name: coolstore
    namespace: rh-forum-2018
  spec: 
    failedBuildsHistoryLimit: 1
    nodeSelector: ~
    output: 
      to: 
        kind: ImageStreamTag
        name: "coolstore:latest"
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source: 
      git: 
        uri: "https://github.com/demo-redhat-forum-2018/monolith.git"
      type: Git
    strategy: 
      sourceStrategy: 
        from: 
          kind: ImageStreamTag
          name: jboss-eap70-openshift:1.4
          namespace: openshift
      type: Source
    successfulBuildsHistoryLimit: 1
    triggers: 
      - 
        type: ConfigChange
      - 
        type: ImageChange
