  apiVersion: v1
  kind: DeploymentConfig
  metadata: 
    labels: 
      app: coolstore
      template: coolstore
    name: coolstore
    namespace: rh-forum-2018
  spec: 
    replicas: 1
    selector: 
      app: coolstore
      deploymentconfig: coolstore
    strategy: 
      activeDeadlineSeconds: 21600
      resources: {}
      type: Recreate
    template: 
      metadata: 
        creationTimestamp: ~
        labels: 
          app: coolstore
          deploymentconfig: coolstore
      spec: 
        containers: 
          - 
            image: "coolstore:ready-for-testing"
            imagePullPolicy: IfNotPresent
            name: coolstore
            ports: 
              - 
                containerPort: 8080
                protocol: TCP
            resources: {}
            terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers: 
      - 
        type: ConfigChange
      - 
        imageChangeParams: 
          containerNames: 
            - coolstore
          from: 
            kind: ImageStreamTag
            name: "coolstore:ready-for-testing"
            namespace: rh-forum-2018
        type: ImageChange
